### ISSUE TITLE
were you github.com/Luis-Hebendanz

### ISSUE THREAD

**Issue by phanirithvij** [Qubasa/infra#1]
Your previous repo was linked here https://wiki.nixos.org/wiki/Configuration_Collection#System_configurations

 as [@luis's NixOS config](https://github.com/Luis-Hebendanz/nix-configs) https://github.com/Luis-Hebendanz/nix-configs

But is this your new repo? if so can you update it? or let me know if I can update it (or if I'm mistaken?)

**Comment by Qubasa** [comment]
@phanirithvij Ah yes you are right, I will update it! Thanks for pointing it out :-)
